# FigRegistry Development Environment
# Follows academic-biology software development guidelines (v2025-05-16)
name: figregistry-dev  # Different name to distinguish from production
channels:
  - conda-forge
  - nodefaults

# Inherit all dependencies from the production environment
# Note: This requires conda >= 4.8.0

dependencies:
  # Inherit all dependencies from the production environment
  - python=3.10
  - pip
  - pydantic>=2.0.0
  - matplotlib>=3.0.0
  - pyyaml>=6.0.0
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0

  # Development Tools
  - pip:
    - -e .[dev]  # Install in development mode with dev dependencies

  # Testing
  - pytest>=7.0.0  # Test framework
  - pytest-cov>=4.0.0  # Test coverage reporting
  - pytest-mock>=3.0.0  # Mocking for tests
  - hypothesis>=6.0.0  # Property-based testing

  # Code Quality
  - black>=23.0.0  # Code formatter
  - isort>=5.0.0  # Import sorter
  - mypy>=1.0.0  # Static type checking
  - ruff>=0.1.0  # Fast Python linter
  - pre-commit>=3.0.0  # Git hooks for code quality
  - interrogate>=1.5.0  # Docstring coverage

  # Documentation
  - ipython>=8.0.0  # Enhanced interactive Python
  - jupyter>=1.0.0  # For example notebooks
  - mkdocs>=1.4.0  # Documentation site generator
  - mkdocs-material>=9.0.0  # Material theme for MkDocs
  - mkdocstrings-python>=0.20.0  # Python API documentation
  - mkdocs-jupyter>=0.24.0  # Support for Jupyter notebooks in docs

  # Optional but useful
  - seaborn>=0.11.0  # Statistical data visualization
  - plotly>=5.0.0  # Interactive plots
  - jupyterlab>=3.0.0  # JupyterLab for development
  - pip-tools>=6.0.0  # For managing pip dependencies

# Create the development environment with:
# conda env create -f environment-dev.yml
# conda activate figregistry-dev

# To update the development environment after changes:
# conda env update -f environment-dev.yml --prune
